import requests, bs4
example_file = open('example.html')
example_soup = bs4.BeautifulSoup(example_file.read(), features="html.parser")
elems = example_soup.select('#author')
print((elems))
print(type(elems))
print(len(elems))
print('-----')
print(elems[0])
print(type(elems[0]))
print(elems[0].get_text())
print(str(elems[0]))
print(elems[0].attrs)

print('-----')
print('-----')
print('-----')

p_elems = example_soup.select('p')
print(str(p_elems[0]))
print(p_elems[0].get_text())
print(str(p_elems[1]))
print(p_elems[1])
print('-----')
print(p_elems[1].get_text())
print(str(p_elems[2]))
print(p_elems[2].get_text())
print()